apiVersion: v1
data:
  password: <base64-password>
  username: <base64-username>
kind: Secret
metadata:
  name: cd-repo
  namespace: flux-system
type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cd-repo
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: cd-repo
  timeout: 60s
  url: https://gitee.com/pada8849/cloud-native.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cd-repo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./chapter-8/app-cd/using
  prune: true
  sourceRef:
    kind: GitRepository
    name: cd-repo
  targetNamespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dapr-component
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./chapter-8/app-cd/using
  prune: true
  sourceRef:
    kind: GitRepository
    name: cd-repo
  targetNamespace: flux-system
