apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    data: jenkins-cache
  name: jenkins-cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    data: jenkins-jar
  name: jenkins-jar
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    data: jenkins-pvc
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
