---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: component-cd
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./chapter-8/app-cd/component
  prune: true
  sourceRef:
    kind: GitRepository
    name: api
  targetNamespace: default
