apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: jsh-api
  name: jsh-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: jsh-api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: jsh-api
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: jsh-mysql
        - name: DB_PASSWD
          value: password
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: JARNAME
          value: jshERP.jar
        - name: REDIS_HOST
          value: jsh-redis
        - name: REDIS_PORT
          value: "6379"
        image: 192.168.1.88:5000/library/jsh-api:1ab4c86
        imagePullPolicy: ""
        name: jsh-api
        ports:
        - containerPort: 9999
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: jsh-api
  name: jsh-api
  namespace: default
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    io.kompose.service: jsh-api
