apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: ops-system
spec:
  interval: 5m
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: "17.8.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ops-system
      interval: 1m
  values:
    architecture: standalone
    master:
      persistence:
        size: 1Gi
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
