apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: jsh-api
  namespace: default
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jsh-api
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: jsh-api
  service:
    # service port number
    port: 9999
    # container port number or name (optional)
    targetPort: 9999
    # Istio gateways (optional)
    gateways:
      - default/seorui-gateway
  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 100
    # canary increment step
    # percentage (0-100)
    stepWeight: 20
    metrics:
      - name: request-success-rate
        # minimum req success rate (non 5xx responses)
        # percentage (0-100)
        thresholdRange:
          min: 99
        interval: 1m
      - name: latency
        templateRef:
          name: latency
          namespace: default
        # maximum req duration P99
        # milliseconds
        thresholdRange:
          max: 500
        interval: 30s
