apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: ops-system
spec:
  interval: 5m
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      version: "4.3.4"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: ops-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true