apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ops-system
spec:
  interval: 5m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "12.2.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ops-system
      interval: 1m
  values:
    architecture: standalone
    primary:
      persistence:
        size: 1Gi
  upgrade:
    remediation:
      remediateLastFailure: false
  test:
    enable: true
