---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: api
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./chapter-3/gitops/yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: api
  targetNamespace: default
