apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jsh-api
  name: jsh-api
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    io.kompose.service: jsh-api
status:
  loadBalancer: {}
