apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jsh-redis
  name: jsh-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jsh-redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: jsh-redis
    spec:
      containers:
      - args:
        - redis-server
        - /home/jsh/redis/redis.conf
        image: 10.0.1.104:5000/jsh/jsh-redis
        imagePullPolicy: ""
        name: jsh-redis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: jsh-redis-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jsh-redis-claim0
        persistentVolumeClaim:
          claimName: jsh-redis-claim0
status: {}
