apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jsh-api
  name: jsh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jsh-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: jsh-api
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: jsh-mysql
        - name: DB_PASSWD
          value: password
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: JARNAME
          value: jshERP.jar
        - name: REDIS_HOST
          value: jsh-redis
        - name: REDIS_PORT
          value: "6379"
        image: 10.0.1.104:5000/jsh/jsh-api:kit
        imagePullPolicy: ""
        name: jsh-api
        ports:
        - containerPort: 9999
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
