apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jsh-mysql
  name: jsh-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jsh-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: jsh-mysql
    spec:
      containers:
      - args:
        - mysqld
        - --innodb-buffer-pool-size=80M
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --default-time-zone=+8:00
        - --lower-case-table-names=1
        env:
        - name: MYSQL_DATABASE
          value: jsh
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: 10.0.1.104:5000/jsh/jsh-mysql
        imagePullPolicy: ""
        name: jsh-mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: jsh-mysql-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jsh-mysql-claim0
        persistentVolumeClaim:
          claimName: jsh-mysql-claim0
status: {}
