apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jsh-web
  name: jsh-web
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: jsh-web
  type: NodePort
status:
  loadBalancer: {}
