apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    data: jenkins-cache
  name: jenkins-cache
  namespace: ops-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
