apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: webhook
  name: webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webhook
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: webhook
    spec:
      containers:
        - env:
            - name: URL
              value: <企微机器人 webhook url>
          image: <镜像仓库>/library/webhook-wework:home
          name: webhook
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: webhook
  name: webhook
  namespace: default
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: webhook
