apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pubsubconfig
spec:
  stateStore:
    - name: postgres
      stateStoreType: postgresql
      metadata:
        - name: host
          value: postgresql.ops-system.svc.cluster.local
        - name: port
          value: "5432"
        - name: database
          value: mydatabase
        - name: user
          value: "postgres"
        - name: password
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password
