apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statepostgresql
  namespace: default
spec:
  type: state.postgresql
  version: v1
  metadata:
    # Connection string
    - name: connectionString
      value: "host=postgresql.ops-system user=postgres password=ZYVpUJVu4F port=5432 connect_timeout=10 database=dapr_test"
