apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pubsubconfig
spec:
  pubsub:
    - name: pubsub
      pubsubType: rabbitmq
      metadata:
        - name: host
          value: rabbitmqsrv
        - name: port
          value: "5672"
        - name: user
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: user
        - name: password
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: password
  stateStore:
    - name: postgres
      stateStoreType: postgresql
      metadata:
        - name: host
          value: postgresqlsrv
        - name: port
          value: "5432"
        - name: database
          value: mydatabase
        - name: user
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: user
        - name: password
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
