apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: blackbox-api
    release: p
  name: blackbox-api
  namespace: cattle-monitoring-system
spec:
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
  selector:
    matchLabels:
      name: blackbox-exporter
  endpoints:
    - interval: 15s
      port: http-metrics
      path: /probe
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __param_module
          targetLabel: module
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __param_target
          targetLabel: target
      params:
        module:
          - http_2xx
        target:
          - http://jsh-api.default:9999/jshERP-boot/platformConfig/getPlatform/name    # Target to probe with http.
    - interval: 15s
      port: http-metrics
      path: /probe
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __param_module
          targetLabel: module
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __param_target
          targetLabel: target
      params:
        module:
          - dns_k8s
        target:
          - 10.43.0.10 # dns ip address
