kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: black
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: jsh-api
  mode: all
  action: pod-failure
  duration: 20m
