apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-data
  namespace: default
  labels:
    app: myapp
data:
  source_txt:
    |-
    file1.txt contents1
    file2.txt contents2
    file3.txt contents3
