apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
    - type: Pod
      max:
        cpu: 1     # 每个 Pod 最多使用 1 个 CPU 核心
        memory: 2Gi  # 每个 Pod 最多使用 2GB 的内存
      min:
        cpu: 100m   # 每个 Pod 至少使用 0.1 个 CPU 核心
        memory: 256Mi  # 每个 Pod 至少使用 256MB 的内存
    - type: Container
      max:
        cpu: 500m   # 每个容器最多使用 0.5 个 CPU 核心
        memory: 512Mi  # 每个容器最多使用 512MB 的内存
      min:
        cpu: 10m    # 每个容器至少使用 0.01 个 CPU 核心
        memory: 32Mi  # 每个容器至少使用 32MB 的内存
      default:
        cpu: 100m   # 如果容器没有指定 CPU 限制，则默认使用 0.1 个 CPU 核心
        memory: 64Mi  # 如果容器没有指定内存限制，则默认使用 64MB 的内存
      defaultRequest:
        cpu: 50m    # 如果容器没有指定 CPU 请求，则默认使用 0.05 个 CPU 核心
        memory: 32Mi  # 如果容器没有指定内存请求，则默认使用 32MB 的内存
