---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: api
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./chapter-3/gitops/yaml/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: api
  targetNamespace: default
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: jsh-api
        spec:
          template:
            spec:
              containers:
              - name: jsh-api
                image: 10.0.1.125:5000/library/api:ac4af36
      target:
        name: api
        kind: Deployment

